import React from 'react';
import { Link, useParams } from 'react-router-dom';
import './Pages.css';

const SUPPORT_EMAIL = 'support@fiilthy.ai';

const PrivacyContent = () => (
  <div className="legal-content">
    <h1>Privacy Policy</h1>
    <p className="legal-updated">Last updated: April 12, 2026</p>

    <h2>1. Information We Collect</h2>
    <p>We collect information you provide directly: email address, name, and payment information when you make a purchase. We also collect usage data such as pages visited, features used, and products generated.</p>

    <h2>2. How We Use Your Information</h2>
    <ul>
      <li>To provide and maintain the FiiLTHY.ai service</li>
      <li>To process payments and deliver digital products</li>
      <li>To send transactional emails (order confirmations, product delivery)</li>
      <li>To improve our AI product generation capabilities</li>
      <li>To detect and prevent fraud or abuse</li>
    </ul>

    <h2>3. Data Storage</h2>
    <p>Your data is stored securely using encrypted databases. API keys you provide are encrypted at rest using industry-standard encryption. We do not sell or share your personal information with third parties for marketing purposes.</p>

    <h2>4. Third-Party Services</h2>
    <p>We use the following third-party services:</p>
    <ul>
      <li><strong>Stripe</strong> — Payment processing. Stripe's privacy policy applies to payment data.</li>
      <li><strong>OpenAI / Anthropic</strong> — AI content generation. Product prompts may be processed by these services.</li>
      <li><strong>SendGrid</strong> — Transactional email delivery.</li>
      <li><strong>Gumroad</strong> — Marketplace publishing (optional).</li>
    </ul>

    <h2>5. Your Rights</h2>
    <p>You may request deletion of your account and associated data by contacting <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. You may export your products at any time from the Products page.</p>

    <h2>6. Cookies</h2>
    <p>We use localStorage to maintain your authentication session. We do not use tracking cookies or third-party advertising trackers.</p>

    <h2>7. Contact</h2>
    <p>For privacy questions, contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
  </div>
);

const TermsContent = () => (
  <div className="legal-content">
    <h1>Terms of Service</h1>
    <p className="legal-updated">Last updated: April 12, 2026</p>

    <h2>1. Acceptance of Terms</h2>
    <p>By accessing FiiLTHY.ai, you agree to these Terms of Service. If you do not agree, do not use the service.</p>

    <h2>2. Service Description</h2>
    <p>FiiLTHY.ai is an AI-powered platform that helps users generate, publish, and sell digital products including eBooks, courses, templates, and planners.</p>

    <h2>3. Account Responsibilities</h2>
    <ul>
      <li>You must provide accurate account information</li>
      <li>You are responsible for maintaining the security of your account credentials</li>
      <li>You must be at least 18 years old to use the service</li>
      <li>You are responsible for all activity under your account</li>
    </ul>

    <h2>4. AI-Generated Content</h2>
    <ul>
      <li>Products generated by the AI are provided as starting points and should be reviewed before publishing</li>
      <li>You own the rights to products you generate using the platform</li>
      <li>You are responsible for ensuring generated content does not infringe on third-party rights</li>
      <li>FiiLTHY.ai does not guarantee the accuracy, completeness, or marketability of AI-generated content</li>
    </ul>

    <h2>5. Payment Terms</h2>
    <ul>
      <li>Payments are processed securely through Stripe</li>
      <li>Prices are displayed in USD unless otherwise stated</li>
      <li>Subscription fees are billed according to the plan selected</li>
    </ul>

    <h2>6. Prohibited Use</h2>
    <p>You may not use FiiLTHY.ai to:</p>
    <ul>
      <li>Generate illegal, harmful, or deceptive content</li>
      <li>Impersonate others or make false claims</li>
      <li>Reverse-engineer or exploit the platform</li>
      <li>Violate any applicable laws or regulations</li>
    </ul>

    <h2>7. Limitation of Liability</h2>
    <p>FiiLTHY.ai is provided "as is" without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>

    <h2>8. Contact</h2>
    <p>For questions about these terms, contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
  </div>
);

const RefundContent = () => (
  <div className="legal-content">
    <h1>Refund Policy</h1>
    <p className="legal-updated">Last updated: April 12, 2026</p>

    <h2>Digital Products</h2>
    <p>Due to the nature of digital products, all sales are final once the product has been delivered or downloaded. However, we want you to be satisfied with your purchase.</p>

    <h2>Eligible Refunds</h2>
    <ul>
      <li><strong>Defective products</strong> — If a purchased product is incomplete, corrupted, or significantly different from its description, you may request a full refund within 14 days of purchase.</li>
      <li><strong>Duplicate charges</strong> — If you were charged multiple times for the same product, we will refund the duplicate charges immediately.</li>
      <li><strong>Technical issues</strong> — If you are unable to access a purchased product due to a platform error, we will either resolve the issue or provide a refund.</li>
    </ul>

    <h2>How to Request a Refund</h2>
    <p>Email <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> with your order confirmation and a description of the issue. We aim to respond within 2 business days.</p>

    <h2>Processing Time</h2>
    <p>Approved refunds are processed within 5-10 business days. The refund will be credited to the original payment method.</p>
  </div>
);

const pages = {
  privacy: PrivacyContent,
  terms: TermsContent,
  refund: RefundContent,
};

export default function LegalPage() {
  const { page } = useParams();
  const Content = pages[page];

  if (!Content) {
    return (
      <div className="page">
        <h1>Page Not Found</h1>
        <p>
          <Link to="/privacy">Privacy Policy</Link> | <Link to="/terms">Terms of Service</Link> | <Link to="/refund">Refund Policy</Link>
        </p>
      </div>
    );
  }

  return (
    <div className="page legal-page">
      <Content />
      <div className="legal-nav">
        <Link to="/privacy">Privacy Policy</Link>
        <Link to="/terms">Terms of Service</Link>
        <Link to="/refund">Refund Policy</Link>
      </div>
    </div>
  );
}
